"""baseline

Revision ID: 792569e4f76b
Revises: 
Create Date: 2026-02-28 00:04:52.471304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792569e4f76b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'start_date')
    op.drop_column('sessions', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('end_date', sa.VARCHAR(), nullable=False))
    op.add_column('sessions', sa.Column('start_date', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
