"""add_deleted_to_players_sessions_divisions_matches

Revision ID: febd118bfcad
Revises: 792569e4f76b
Create Date: 2026-02-28 00:06:19.509338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febd118bfcad'
down_revision: Union[str, Sequence[str], None] = '792569e4f76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divisions', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('matches', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('sessions', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.drop_column('sessions', 'start_date')
    op.drop_column('sessions', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('end_date', sa.VARCHAR(), nullable=False))
    op.add_column('sessions', sa.Column('start_date', sa.VARCHAR(), nullable=False))
    op.drop_column('sessions', 'deleted')
    op.drop_column('players', 'deleted')
    op.drop_column('matches', 'deleted')
    op.drop_column('divisions', 'deleted')
    # ### end Alembic commands ###
